apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-genai-orchestrator'
  labels:
    app.kubernetes.io/name: genai-orchestrator
    app.kubernetes.io/component: genai-orchestrator
    app.kubernetes.io/part-of: tock
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: genai-orchestrator
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/resource: deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/component: genai-orchestrator
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/resource: deployment
    spec:
      {{- include "genAiOrchestrator.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.genAiOrchestrator.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.genAiOrchestrator.podSecurityContext "enabled" | toYaml | nindent 10 }}
      {{- end }}
      {{- if or .Values.genAiOrchestrator.langchain.tiktokencache.enabled .Values.genAiOrchestrator.truststore.enabled }}
      initContainers:
      {{- if .Values.genAiOrchestrator.langchain.tiktokencache.enabled }}
      - name: init-tiktoken
        image: {{ include "genAiOrchestrator.langchain.tiktokencache.image" . }}
        {{- if .Values.global.initContainerImage.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.global.initContainerImage.containerSecurityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
        command: ["sh", "-c"]
        args:
          - |
            set -euo pipefail
            # mkdir -p /cache
            cp -v /tiktoken/* /cache/
            # Permissions larges si l'app tourne sous un autre UID
            # chmod -R a+rX /cache
        volumeMounts:
        - name: tiktoken-cache
          mountPath: /cache
        {{- if .Values.genAiOrchestrator.resources }}
        resources: {{- toYaml .Values.genAiOrchestrator.resources | nindent 12 }}
        {{- end }}
      {{- end }}
      {{- if .Values.genAiOrchestrator.truststore.enabled }}
      - name: truststore-generator
        image: {{ include "truststoreContainer.image" . }}
        {{- if .Values.global.truststoreContainerImage.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.global.truststoreContainerImage.containerSecurityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
        command: ["/bin/sh", "-c"]
        args:
            - |
              keytool -importcert -noprompt \
                -file /etc/ssl/certs/{{ .Values.genAiOrchestrator.truststore.certSecret }}.crt \
                -alias corp-root \
                -keystore /truststore/truststore.jks \
                -storepass changeit;
        volumeMounts:
            - name: cert-volume
              mountPath: /etc/ssl/certs/{{ .Values.genAiOrchestrator.truststore.certSecret }}.crt
              subPath: {{ .Values.genAiOrchestrator.truststore.certSecret }}.crt
              readOnly: true
            - name: truststore-volume
              mountPath: /truststore
      {{- if .Values.genAiOrchestrator.resources }}
        resources: {{- toYaml .Values.genAiOrchestrator.resources | nindent 12 }}
      {{- end }}
      {{- end }}
      {{- end }}
      containers:    
        - name: genai-orchestrator
          image: {{ include "genAiOrchestrator.image" . }}
          {{- if .Values.genAiOrchestrator.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.genAiOrchestrator.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: genaiport
              containerPort: 8000
#          livenessProbe:
#            httpGet:
#              path: /healthcheck
#              port: 8000
#            initialDelaySeconds: 180
#            timeoutSeconds: 5 # Defaults to 1
#            periodSeconds: 20 # Defaults to 10
#            failureThreshold: 3 # Defaults to 3
          volumeMounts:
              - mountPath: /tmp
                name: tmp-volume
          {{- if .Values.genAiOrchestrator.langchain.tiktokencache.enabled }}
              - mountPath: /cache
                name: tiktoken-cache
          {{- end }}
          {{- if .Values.genAiOrchestrator.truststore.enabled }}
              - mountPath: /etc/ssl/certs/{{ .Values.genAiOrchestrator.truststore.certSecret }}.crt
                name: cert-volume
                readOnly: true
                subPath: {{ .Values.genAiOrchestrator.truststore.certSecret }}.crt
          {{- end }}
          env:
             - name: IS_HELM
               value: "true"
          {{- if .Values.genAiOrchestrator.truststore.enabled }}
             - name: REQUESTS_CA_BUNDLE
               value: /etc/ssl/certs/{{ .Values.genAiOrchestrator.truststore.certSecret }}.crt
             - name: SSL_CERT_FILE
               value: /etc/ssl/certs/{{ .Values.genAiOrchestrator.truststore.certSecret }}.crt         
          {{- end }}
          {{- if .Values.genAiOrchestrator.langchain.tiktokencache.enabled }}
            - name: TIKTOKEN_CACHE_DIR
              value: /cache
          {{- end }}
          envFrom:
            - configMapRef:
                name: '{{ .Release.Name }}-genai-orchestrator-cfg'
      {{- if .Values.genAiOrchestrator.resources }}
          resources: {{- toYaml .Values.genAiOrchestrator.resources | nindent 14 }}
      {{- end }}
      volumes:
          - name: tmp-volume
            emptyDir: {}
          {{- if .Values.genAiOrchestrator.langchain.tiktokencache.enabled }}
          - name: tiktoken-cache
            emptyDir: {}
          {{- end }}
          {{- if .Values.genAiOrchestrator.truststore.enabled }}
          - name: cert-volume
            secret:
              secretName: {{ .Values.genAiOrchestrator.truststore.certSecret }}
          - name: truststore-volume
            emptyDir: {}
          {{- end }}  
    {{- with .Values.genAiOrchestrator.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.genAiOrchestrator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.genAiOrchestrator.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}