{{- if .Values.global.NetworkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name:  '{{ .Release.Name }}-tock-netpolicy'
  labels:
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: tock
spec:
#  podSelector:
#    matchLabels:
#      app.kubernetes.io/instance: {{ .Release.Name }}
  podSelector: {}
  ingress: 
  - {}
  egress: 
  - {}
  policyTypes:
   - Ingress
   - Egress
  {{- end }}